# Generated by Django 4.2.16 on 2024-11-18 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_avis_user_rename_steps_recipe_instructions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="ingredient", old_name="description", new_name="qté",
        ),
        migrations.RemoveField(model_name="ingredient", name="name",),
        migrations.AddField(
            model_name="ingredient",
            name="recette",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.recipe",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ingredient",
            name="produit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.produit",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(to="recipes.produit"),
        ),
    ]
