# Generated by Django 5.1.3 on 2024-11-21 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipe_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='recette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe'),
        ),
    ]
